### PR TITLE
Merge pull request #2 from PoweredRails/master

### PR DESCRIPTION
**Pull request by Web2201**
Merge with base

### CODE REVIEW

**Comment by phase** [comment]
You merged a commit that merged this pull request, which contained a commit that merged this pull request, which contained a commit that merged this pull request, which contained a commit that merged this pull request, which contained a commit that merged this pull request...

oh wait wut

**Comment by Web2201** [comment]
wut -.-

**Comment by Web2201** [comment]
PS: This is nothing to worry about, it's just how I merge my fork with this thing.

**Comment by NoneVale** [comment]
I'm confused now

**Pull request merged**
